apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondary-deployment
  #namespace: prisma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prisma-secondary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prisma-secondary
    spec:
      containers:
        - name: prisma-secondary
          image: prismagraphql/prisma-prod:1.34 
          imagePullPolicy: Always
          resources: # CHANGE THIS AS NEEDED
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "100m"
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx1400m"
            - name: ENV
              value: "prod"
            - name: PRISMA_CONFIG
              value: | # CHANGE THIS AS NEEDED
                port: 4466
                managementApiSecret: "MuchSecret"
                enableManagementApi: "true"
                server2serverSecret: "SuperSecretWow"
                rabbitUri: "amqp://user:3TdZMnYGqx@rabbitmq.default.svc.cluster.local:5672"
                databases:
                  default:
                    connector: mongo
                    uri: mongodb://mongodb-mongodb-replicaset.default.svc.cluster.local:27017
                    active: "true"                    
                    connectionLimit: 20
                    database: "prisma"
                    managementSchema: "prisma"
                    ssl: false         
          ports:
            - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-secondary-service
  #namespace: prisma
spec:
  selector: 
    app: prisma-secondary
  type: ClusterIP
  ports:
    - name: http
      port: 4466
      targetPort: 4466
      protocol: TCP

