apiVersion: v1
kind: Service
metadata:
  name: prisma-express
spec:
  selector: 
    app: graphql-prisma
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
