apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jerilcj3/python:VERSION
        ports:
        - name: port1
          containerPort: 4200
        - name: port2
          containerPort: 4201
        - name: port3
          containerPort: 4202
        - name: port4
          containerPort: 4203
        - name: port5
          containerPort: 4204
        - name: port6
          containerPort: 4205
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: python-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
  - name: port1
    port: 4200
    targetPort: 4200
  - name: port2
    port: 4201
    targetPort: 4201
  - name: port3
    port: 4202
    targetPort: 4202
  - name: port4
    port: 4203
    targetPort: 4203
  - name: port5
    port: 4204
    targetPort: 4204
  - name: port6
    port: 4205
    targetPort: 4205
  selector:
    app: backend
