version: '3.7'

services:
  mongo-express:
   image: mongo-express
   container_name: mongo-express
   ports:
     - "8081:8081"
   environment:
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_MONGODB_PORT=27017
   networks:
     - prisma
    
  mongodb:
   image: mongo:4.2 
   container_name: mongodb
   volumes:
     - ./mongo-volume:/data/db
   ports:
     - "27017:27017"    
   networks:
     - prisma
   
  prisma-server:
   image: prismagraphql/prisma:1.34.10
   container_name: prisma-server
   restart: always
   ports:
     - "4466:4466"
   environment:
     PRISMA_CONFIG: |
       port: 4466
       databases:
         default:
           connector: mongo
           uri: mongodb://mongodb
   networks:
     - prisma 

volumes:
 mongo-volume: ~

networks:
 prisma:
   name: prisma
   driver: bridge

