apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    stage: production
    name: prisma
    app: prisma
data:
  PRISMA_CONFIG_PRIMARY: |
    port: 4466
    managementApiSecret: "MuchSecret"
    enableManagementApi: "true"
    server2serverSecret: "SuperSecretWow"
    rabbitUri: "amqp://rabbitmq.default.svc.cluster.local:5672"
    databases:
      default:
        connector: mongo
        uri: mongodb://jeriljose:M!cr0507t@mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local:27017/<mydb>?replicaSet=mongo?authSource=admin 
        active: "true"
        connectionLimit: 20
        database: "prisma"
        managementSchema: "prisma"
        ssl: false

  PRISMA_CONFIG_SECONDARY: |
    port: 4466
    managementApiSecret: "MuchSecret"
    enableManagementApi: "false"
    server2serverSecret: "SuperSecretWow"
    rabbitUri: "amqp://rabbitmq.default.svc.cluster.local:5672"
    databases:
      default:
        connector: mongo
        uri: mongodb://jeriljose:M!cr0507t@mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local:27017/<mydb>?replicaSet=monogo?authSource=admin 
        active: "true"
        connectionLimit: 20
        database: "prisma"
        managementSchema: "prisma"
        ssl: false       
