apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondary-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prisma-secondary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prisma-secondary
    spec:
      containers:
        - name: prisma-secondary
          image: prismagraphql/prisma-prod:1.34 
          imagePullPolicy: Always
          resources: # CHANGE THIS AS NEEDED
           requests:
             memory: "1Gi"
             cpu: "100m"
           limits:
             memory: "1Gi"
             cpu: "100m"
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx1400m"
            - name: ENV
              value: "prod"
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG_SECONDARY  
          ports:
            - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-secondary-service
  namespace: default
spec:
  selector: 
    app: prisma-secondary
  type: ClusterIP
  ports:
    - name: http
      port: 4466
      targetPort: 4466
      protocol: TCP

