apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment
  #namespace: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma-primary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prisma-primary
    spec:
      containers:
        - name: prisma-primary
          image: prismagraphql/prisma-prod:1.34
          imagePullPolicy: Always
          resources: # CHANGE THIS AS NEEDED
          # requests:
          #   memory: "1Gi"
          #   cpu: "100m"
          # limits:
          #   memory: "1Gi"
          #   cpu: "100m"
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx800m" # CHANGE THIS AS NEEDED
            - name: ENV
              value: "prod"
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG_PRIMARY
          ports:
            - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-primary-service
  #namespace: prisma
spec:
  selector: 
    app: prisma-primary
  type: ClusterIP
  ports:
    - name: http
      port: 4466
      targetPort: 4466
      protocol: TCP

