apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    stage: production
    name: prisma
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    managementApiSecret: "MuchSecret"
    enableManagementApi: "true"
    server2serverSecret: "SuperSecretWow"
    rabbitUri: "amqp://user:emqunU9Sb0@rabbitmq.default.svc.cluster.local:5672"
    databases:
      default:
        connector: mongo
        uri: mongodb://mongodb-mongodb-replicaset.default.svc.cluster.local:27017 
        active: "true"
        connectionLimit: 20
        database: "prisma"
        managementSchema: "prisma"
        ssl: false
